// Code generated by "stringer -type=returnCode"; DO NOT EDIT.

package anidb

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[illegalInput-505]
	_ = x[banned-555]
	_ = x[unknownCmd-598]
	_ = x[internalErr-600]
	_ = x[outOfService-601]
	_ = x[serverBusy-602]
	_ = x[timeout-604]
	_ = x[loginFirst-501]
	_ = x[accessDenied-502]
	_ = x[invalidSession-506]
}

const (
	_returnCode_name_0 = "loginFirstaccessDenied"
	_returnCode_name_1 = "illegalInputinvalidSession"
	_returnCode_name_2 = "banned"
	_returnCode_name_3 = "unknownCmd"
	_returnCode_name_4 = "internalErroutOfServiceserverBusy"
	_returnCode_name_5 = "timeout"
)

var (
	_returnCode_index_0 = [...]uint8{0, 10, 22}
	_returnCode_index_1 = [...]uint8{0, 12, 26}
	_returnCode_index_4 = [...]uint8{0, 11, 23, 33}
)

func (i returnCode) String() string {
	switch {
	case 501 <= i && i <= 502:
		i -= 501
		return _returnCode_name_0[_returnCode_index_0[i]:_returnCode_index_0[i+1]]
	case 505 <= i && i <= 506:
		i -= 505
		return _returnCode_name_1[_returnCode_index_1[i]:_returnCode_index_1[i+1]]
	case i == 555:
		return _returnCode_name_2
	case i == 598:
		return _returnCode_name_3
	case 600 <= i && i <= 602:
		i -= 600
		return _returnCode_name_4[_returnCode_index_4[i]:_returnCode_index_4[i+1]]
	case i == 604:
		return _returnCode_name_5
	default:
		return "returnCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
