// Code generated by "stringer -type=ReturnCode -linecomment"; DO NOT EDIT.

package udpapi

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LoginFirst-501]
	_ = x[AccessDenied-502]
	_ = x[IllegalInput-505]
	_ = x[InvalidSession-506]
	_ = x[Banned-555]
	_ = x[UnknownCmd-598]
	_ = x[InternalErr-600]
	_ = x[OutOfService-601]
	_ = x[ServerBusy-602]
	_ = x[Timeout-604]
}

const (
	_ReturnCode_name_0 = "501 LOGIN_FIRST502 ACCESS_DENIED"
	_ReturnCode_name_1 = "505 ILLEGAL_INPUT_OR_ACCESS_DENIED506 INVALID_SESSION"
	_ReturnCode_name_2 = "555 BANNED"
	_ReturnCode_name_3 = "598 UNKNOWN_COMMAND"
	_ReturnCode_name_4 = "600 INTERNAL_SERVER_ERROR601 ANIDB_OUT_OF_SERVICE602 SERVER_BUSY"
	_ReturnCode_name_5 = "604 TIMEOUT - DELAY AND RESUBMIT"
)

var (
	_ReturnCode_index_0 = [...]uint8{0, 15, 32}
	_ReturnCode_index_1 = [...]uint8{0, 34, 53}
	_ReturnCode_index_4 = [...]uint8{0, 25, 49, 64}
)

func (i ReturnCode) String() string {
	switch {
	case 501 <= i && i <= 502:
		i -= 501
		return _ReturnCode_name_0[_ReturnCode_index_0[i]:_ReturnCode_index_0[i+1]]
	case 505 <= i && i <= 506:
		i -= 505
		return _ReturnCode_name_1[_ReturnCode_index_1[i]:_ReturnCode_index_1[i+1]]
	case i == 555:
		return _ReturnCode_name_2
	case i == 598:
		return _ReturnCode_name_3
	case 600 <= i && i <= 602:
		i -= 600
		return _ReturnCode_name_4[_ReturnCode_index_4[i]:_ReturnCode_index_4[i+1]]
	case i == 604:
		return _ReturnCode_name_5
	default:
		return "ReturnCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
